### ISSUE TITLE
Duplicate Project?

### ISSUE THREAD

**Issue by shawnholt** [veda-consulting/uk.co.vedaconsulting.pcpteams#195]
I noticed this: https://github.com/mlutfy/ca.bidon.pcpteams
is it a duplicate/rewrite or something different?

**Comment by seanmadsen** [comment]
They are distinct projects with coincidental names, aiming for similar functionality.

(I'm not affiliated with either project, but I'm evaluating both of them for potential use.)

**Comment by veda-consulting** [comment]
hi Sean

We're not sure about the other project - its not ours as such

Parvez Saleh

Managing Director

 vedaconsulting.co.uk

 +44 (0) 33 3011 8874 <#UNIQUE_ID_SafeHtmlFilter_>

 90 Mainyard, 90 Wallis Rd
London, E9 5LN

<https://twitter.com/vedaconsulting>
<https://www.facebook.com/vedaconsulting>
<https://uk.linkedin.com/in/vedaconsulting>

**Comment by veda-consulting** [comment]
@shawnholt if you need anything else give us a shout. Closing this issue.
