### ISSUE TITLE
Fatal error: Call to undefined method CRM_Core_BAO_UFGroup::findContact()

### ISSUE THREAD

**Issue by herbdool** [veda-consulting/uk.co.vedaconsulting.pcpteams#204]
On this screen "Thanks , MY XXX TEAM is now set up. You can now invite others to join you."

```
Fatal error: Call to undefined method CRM_Core_BAO_UFGroup::findContact() in /XXX/sites/all/civicrm_custom/extensions/uk.co.vedaconsulting.pcpteams/CRM/Pcpteams/Utils.php on line 469
```

**Comment by mathavanveda** [comment]
CRM_Core_BAO_UFGroup::findContact()  is a part of civicrm core https://github.com/mathavanveda/civicrm-core/blob/master/CRM/Core/BAO/UFGroup.php#L925, not sure how do you end up with this error unless some issues from civicrm installation..

**Comment by deepak-srivastava** [comment]
This has been fixed in latest commit - https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams/commit/4106bad4a72f86ab4e8404de1fd70d6cebb6b8c3
