### ISSUE TITLE
How to enable donation button for public?

### ISSUE THREAD

**Issue by herbdool** [veda-consulting/uk.co.vedaconsulting.pcpteams#205]
I've run out of idea of having the donation button show up on the PCP page. What are the steps / configuration required to have it show up?

**Comment by deepak-srivastava** [comment]
The extension doesn't expose it's pcp-manage page for public, which is based on the idea that CMS will have its own public facing pages.
However i do think option should be available for users to decide.

If you are ok to dive into code, here is how you can expose pcp-manage screen to public, that also includes a donate button - https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams/commit/3b97bca5d41d668f7d619eef6a99dd9a53c3d000. Note this requires rebuilding civicrm menu.
To convert it into an option for users to choose from, it would need some more code.

**Comment by deepak-srivastava** [comment]
PC manage page is now available for public - https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams/commit/e708d27a1ad147ab55e8d871ac99364b458d3752
