### ISSUE TITLE
What is EP1 and EP1A?

### ISSUE THREAD

**Issue by seanmadsen** [veda-consulting/uk.co.vedaconsulting.pcpteams#211]
I'm evaluating this extension for potential use and trying to understand how it works...

This extension adds the following "event links" to each event: 

* "PCP register for event (EP1)"
* "PCP already has a place (EP1A)"

What do these links do? What is the difference between them? What do the codes "EP1" and "EP1A" mean?

**Comment by veda-consulting** [comment]
@seanmadsen @KarinG is making some fixes/changes
@KarinG if you come across these labels and if you can see where they are coming from please to update

**Comment by twomice** [comment]
* These links are added in [templates/CRM/Event/Page/ManageEvent.extra.tpl](https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams/blob/master/templates/CRM/Event/Page/ManageEvent.extra.tpl) and [templates/CRM/Event/Form/ManageEvent/Tab.extra.tpl](https://github.com/veda-consulting/uk.co.vedaconsulting.pcpteams/blob/master/templates/CRM/Event/Form/ManageEvent/Tab.extra.tpl)
* They point to the same URL, except that "EP1A" adds the query parameter `code=cpftq` (but it's unclear so far what that does).

Any clues from @veda-consulting ?
